version: '3.8'
services:
  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    depends_on:
      - auth-db

  ticket-order-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ticket_order_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - ticket-order-db-data:/var/lib/postgresql/data

  ticket-order-service:
    build:
      context: ./ticket-order-service
      dockerfile: Dockerfile
    ports:
      - '8082:8080'
    depends_on:
      - ticket-order-db

volumes:
  auth-db-data:
  ticket-order-db-data:
